### PR TITLE
Support Trend as a number and now as a string, Dexcom EU changed the type of Trend to string

### PR DESCRIPTION
**Pull request by cpitchford**
At 2021-11-30 17:00+UTC I found that, in the EU region, the Dexcom API switched the format of the Trend property.

Where as previously, the Trend property was a number, it is now a string. This breaks the direction feature.

here's a snip from my logs after the change:

```
Entries [ {
  WT: 'Date(1638301612000)',
  ST: 'Date(1638301612000)',
  DT: 'Date(1638301612000+0000)',
  Value: 84,
  Trend: 'Flat' // Previously this would've been 4
}
```

This change converts the string value back to an integer by finding the correct value in the DIRECTIONS object.

This restores the direction feature

It is unlikely to be rigorous since I don't now all the string values Dexcom will now return for Trend, but it certainly works for common values (up arrows, down arrows and flat)

### CODE REVIEW

**Comment by cpitchford** [comment]
This patch resolves https://github.com/nightscout/share2nightscout-bridge/issues/52

**Comment by p-kimberley** [comment]
@cpitchford Good spot. I've observed this too. US users don't appear to be affected...yet.

The only trend string I haven't yet seen is the equivalent of `9`, or "RateOutOfRange".

Think you'll need to adjust your conversion method for `"NOT COMPUTABLE"` which in the API response, is now `"NotComputable"`. Same for `"NONE"`, which is `"None"`. Think it's safe to say they've gone for SentenceCase for all values.

**Comment by cpitchford** [comment]
Good point, I'm still getting fully up to speed!

I've added some code to match the string trend after converted to lowercase and removing spaces. This should cover all eventualities , save the prospect of an entirely new string appearing. This might be worth logging if we happen to fail to match?

**Comment by bewest** [comment]
Thanks for improving this!  I've retargeted the `dev` branch.

**Comment by PieterGit** [comment]
@cpitchford Great work! I was just figuring out why I saw Unicode Character “⇼” (U+21FC) in the direction field in Nightscout. Figured out it was caused by https://github.com/nightscout/cgm-remote-monitor/blob/46418c7ff275ae80de457209c1686811e033b5dd/lib/plugins/direction.js#L54 but then saw you and @bewest created a new share2nightscout-bridge and Nightscout release. Thanks a lot.

**Pull request merged**
