### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by bewest**
Prepare for next impending release to handle changes to Dexcom Share trend values.

### CODE REVIEW

**Comment by bewest** [comment]
Works for me, but I'm testing using a US-based account.

**Comment by bjornoleh** [comment]
> Works for me, but I'm testing using a US-based account.

@bewest , I can test with an OUS account if needed.

I failed to get it working by deploying share2nightscout to Heroku, not sure what the issue was there. But I can easliy test in Nightscout cgm monitor as soon as it is available in dev there.

**Comment by cpitchford** [comment]
@bewest I've tested using my EU/UK account. My login is a username, not email address. I think that's an old type, but not sure.

No problems using the copy from the dev branch

**Comment by bewest** [comment]
Thanks to everyone, especially @cpitchford, for helping with these changes.  Version `0.2.8` of the plugin is published on npm. https://www.npmjs.com/package/share2nightscout-bridge

**Comment by bewest** [comment]
Dev branch of cgm-remote-monitor now depends on this new version: https://github.com/nightscout/cgm-remote-monitor/pull/7146.

**Comment by bewest** [comment]
Howdy all, I've left some notes about the kind of testing that would be very helpful with the dev branch here: https://github.com/nightscout/cgm-remote-monitor/pull/7146#issuecomment-984195926

**Pull request merged**
